<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>tflite_example</name>
  <version>0.0.0</version>
  <description>Examples using the tflite package</description>
  <maintainer email="sgvandijk@gmail.com">Sander G. van Dijk</maintainer>
  <license>Apache License 2.0</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <exec_depend>image_publisher</exec_depend>
  <exec_depend>v4l2_camera</exec_depend>
  <exec_depend>launch</exec_depend>
  <exec_depend>python3-imageio</exec_depend>
  <exec_depend>rqt-image-view</exec_depend>
  <exec_depend>tflite</exec_depend>
  <exec_depend>tflite_util</exec_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>  
